// <auto-generated />
using LMSPO.SqlServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LMSPO.SqlServer.Migrations
{
    [DbContext(typeof(LMSDbContext))]
    [Migration("20231003090149_api")]
    partial class api
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LMSPO.CoreBusiness.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            CustomerName = "Vejle Kommune"
                        },
                        new
                        {
                            CustomerId = 2,
                            CustomerName = "Herning Kommune"
                        });
                });

            modelBuilder.Entity("LMSPO.CoreBusiness.Entities.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("EAN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GroupId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("LMSPO.CoreBusiness.Entities.GroupProduct", b =>
                {
                    b.Property<int>("GroupProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupProductId"));

                    b.Property<int>("AddedQuantity")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("PurchasedProductId")
                        .HasColumnType("int");

                    b.HasKey("GroupProductId");

                    b.HasIndex("GroupId");

                    b.HasIndex("PurchasedProductId");

                    b.ToTable("GroupProducts");
                });

            modelBuilder.Entity("LMSPO.CoreBusiness.Entities.PurchasedProduct", b =>
                {
                    b.Property<int>("PurchasedProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PurchasedProductId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("PurchasedQty")
                        .HasColumnType("int");

                    b.HasKey("PurchasedProductId");

                    b.HasIndex("CustomerId");

                    b.ToTable("PurchasedProducts");

                    b.HasData(
                        new
                        {
                            PurchasedProductId = 1,
                            CustomerId = 1,
                            ProductName = "Product A",
                            ProductPrice = 10.99m,
                            PurchasedQty = 2
                        },
                        new
                        {
                            PurchasedProductId = 2,
                            CustomerId = 2,
                            ProductName = "Product B",
                            ProductPrice = 19.99m,
                            PurchasedQty = 4
                        });
                });

            modelBuilder.Entity("LMSPO.CoreBusiness.Entities.Group", b =>
                {
                    b.HasOne("LMSPO.CoreBusiness.Entities.Customer", "Customer")
                        .WithMany("Groups")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("LMSPO.CoreBusiness.Entities.GroupProduct", b =>
                {
                    b.HasOne("LMSPO.CoreBusiness.Entities.Group", "Group")
                        .WithMany("GroupProducts")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LMSPO.CoreBusiness.Entities.PurchasedProduct", "PurchasedProduct")
                        .WithMany("GroupProducts")
                        .HasForeignKey("PurchasedProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("PurchasedProduct");
                });

            modelBuilder.Entity("LMSPO.CoreBusiness.Entities.PurchasedProduct", b =>
                {
                    b.HasOne("LMSPO.CoreBusiness.Entities.Customer", "Customer")
                        .WithMany("PurchasedProducts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("LMSPO.CoreBusiness.Entities.Customer", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("PurchasedProducts");
                });

            modelBuilder.Entity("LMSPO.CoreBusiness.Entities.Group", b =>
                {
                    b.Navigation("GroupProducts");
                });

            modelBuilder.Entity("LMSPO.CoreBusiness.Entities.PurchasedProduct", b =>
                {
                    b.Navigation("GroupProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
